### PR TITLE
add io.SeekEnd support

### PR DESCRIPTION
**Pull request by yxxhero**
add io.SeekEnd support

### CODE REVIEW

**Comment by yxxhero** [comment]
@nikolaydubina should I fix the test error? I saw all the past PRs. all failed.

**Comment by nikolaydubina** [comment]
hey, thanks for pointing this out!

I think io.SeekEnd does not mean we are jumping to end of reader.

instead, it means that we are counting offset relatively to the end of reader. 

this means, we have to consider offset. https://pkg.go.dev/io#SeekEnd

other discussions on mechanics
* https://github.com/golang/go/issues/53474


also, we need test for this. do you mind to add test for this behavior as well? (I just broken tests due to security leak of my AWS tokens, so if you figure out how to use anonymous credentials: https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/credentials#AnonymousCredentials + some public file, file used now should also be public, but if you find better file it is also good :) )

**Comment by nikolaydubina** [comment]
past PRs failed mostly because of Dependabot. I configured both A) Dependabot and B) approved GitHub Actions to use my same AWS tokens.

but this is not good. I dropped my tokens now. we need to use anonymous credentials for this pipeline.

**Comment by yxxhero** [comment]
@nikolaydubina updated. please see the logic. if it's ok, I will add tests.

**Comment by nikolaydubina** [comment]
I thinks this is about right. now need tests for this. please rebase, I fixed tests!

**Comment by yxxhero** [comment]
Thanks. I have done it.

**Comment by yxxhero** [comment]
@nikolaydubina tests added.

**Review by nikolaydubina — APPROVED** [review]
yes, this would do! thanks for adding this!

**Pull request merged**
